apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: gad-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: gad-app
    spec:
      containers:
      - name: gad-app
        image: 860705619849.dkr.ecr.us-east-1.amazonaws.com/sangini/gadrepo:3
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: gad-service
spec:
  selector:
    app: gad-app
  ports:
    - port: 8082
      targetPort: 8082
